In [2]:
import numpy as np
import pandas as pd
import re

data = pd.read_excel(r"C:\Users\Damilola Ologunagba\Desktop\NewTM.xlsx", "Sheet3")

In [3]:
len(data.Formula.unique())

754

In [4]:
#data.drop_duplicates(subset=['Formula'], keep=False)
datax = data.drop_duplicates(subset='Formula', keep="first")
pd.set_option('display.max_rows', None)
datax = datax.reset_index(drop=True)
datax.head()

   Formula  Formation Energy (eV)
0  Al2CrFe                  2.471
1  Al2CrTc                  2.714
2   Al2VIr                  2.600
3  AlCrTc2                  3.306
4    AlV2W                  3.756

In [5]:
datax.to_excel(r'C:\Users\Damilola Ologunagba\Desktop\Data3.xlsx', index = False)

In [6]:
elem_data = pd.read_excel(r"C:\Users\Damilola Ologunagba\Desktop\MLDATA\trimetallics.xlsx", "Sheet1")

In [7]:
elem_data = elem_data.drop_duplicates(subset ="System",
                     keep = 'first')

In [8]:
elem_data['Host electron affinity'] = elem_data['Host electron affinity'].fillna(0)

In [9]:
pd.set_option('display.max_rows', None)
elem_data.reset_index(drop=True)
elem_data.head()

,System,Host radius(pm),Host volume,Host atomic number,Host atomic mass,Host period,Host ionization energy(KJ/mol),Host density(Kg/m3),Host electron affinity,Host work function(eV),Host pauling electronegativity
0,Ag,160,1.715951e+07,47,107.868,5,731,10490,1.303,4.26,1.93
1,Al,125,8.182292e+06,13,26.9815,3,577.54,2700,0.442,4.28,1.61
2,Au,135,1.030733e+07,79,196.967,6,890.13,19300,2.309,5.10,2.54
3,Be,105,4.849677e+06,4,9.01218,2,899.5,1848,-0.190,4.98,1.57
4,Bi,0,0.000000e+00,0,0,0,0,0,0.000,0.00,0

In [10]:
sys_data = datax[["Formula"]]
sys_data = sys_data.reset_index(drop=True)
sys_data.head()

   Formula
0  Al2CrFe
1  Al2CrTc
2   Al2VIr
3  AlCrTc2
4    AlV2W

In [11]:
sys_split = sys_data['Formula'].str.findall('[A-Z][^A-Z]*')
sys_data['newdata'] = sys_split

In [12]:
sys_data = sys_data.reset_index(drop=True)
sys_data.head()

   Formula        newdata
0  Al2CrFe  [Al2, Cr, Fe]
1  Al2CrTc  [Al2, Cr, Tc]
2   Al2VIr   [Al2, V, Ir]
3  AlCrTc2  [Al, Cr, Tc2]
4    AlV2W    [Al, V2, W]

In [13]:
sys_data_new = pd.DataFrame(sys_data.newdata.values.tolist()).add_prefix('sys_')

In [14]:
sys_data_new["sys_0"] = sys_data_new.sys_0.str.replace('2','')
sys_data_new["sys_1"] = sys_data_new.sys_1.str.replace('2','')
sys_data_new["sys_2"] = sys_data_new.sys_2.str.replace('2','')

In [15]:
sys_data_new.head()

  sys_0 sys_1 sys_2
0    Al    Cr    Fe
1    Al    Cr    Tc
2    Al     V    Ir
3    Al    Cr    Tc
4    Al     V     W

In [16]:
sys_data_new_1 = sys_data_new[["sys_0"]]
sys_data_new_2 = sys_data_new[["sys_1"]]
sys_data_new_3 = sys_data_new[["sys_2"]]

In [17]:
sys_data_new_1["Host radius(pm)"], sys_data_new_1["Host volume"], sys_data_new_1["Host atomic number"], sys_data_new_1["Host atomic mass"], sys_data_new_1["Host period"], sys_data_new_1["Host ionization energy(KJ/mol)"], sys_data_new_1["Host density(Kg/m3)"], sys_data_new_1["Host electron affinity"], sys_data_new_1["Host work function(eV)"], sys_data_new_1["Host pauling electronegativity"] = ['','','','','','','','','','']
sys_data_new_2["Host radius(pm)"], sys_data_new_2["Host volume"], sys_data_new_2["Host atomic number"], sys_data_new_2["Host atomic mass"], sys_data_new_2["Host period"], sys_data_new_2["Host ionization energy(KJ/mol)"], sys_data_new_2["Host density(Kg/m3)"], sys_data_new_2["Host electron affinity"], sys_data_new_2["Host work function(eV)"], sys_data_new_2["Host pauling electronegativity"] = ['','','','','','','','','','']
sys_data_new_3["Host radius(pm)"], sys_data_new_3["Host volume"], sys_data_new_3["Host atomic number"], sys_data_new_3["Host atomic mass"], sys_data_new_3["Host period"], sys_data_new_3["Host ionization energy(KJ/mol)"], sys_data_new_3["Host density(Kg/m3)"], sys_data_new_3["Host electron affinity"], sys_data_new_3["Host work function(eV)"], sys_data_new_3["Host pauling electronegativity"] = ['','','','','','','','','','']

C:\Users\Damilola Ologunagba\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Damilola Ologunagba\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Damilola Ologunagba\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [18]:
sys_data_new_11 = sys_data_new_1.merge(elem_data,
                                       left_on='sys_0',
                                       right_on='System',
                                       how='left')
sys_data_new_11 = sys_data_new_11.drop(sys_data_new_11.columns[[1,2,3,4,5,6,7,8,9,10,11]], axis=1)
sys_data_new_11.head()

,sys_0,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,Host work function(eV)_y,Host pauling electronegativity_y
0,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,1.61
1,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,1.61
2,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,1.61
3,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,1.61
4,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,1.61

In [19]:
sys_data_new_12 = sys_data_new_2.merge(elem_data,
                                       left_on='sys_1',
                                       right_on='System',
                                       how='left')
sys_data_new_12 = sys_data_new_12.drop(sys_data_new_12.columns[[1,2,3,4,5,6,7,8,9,11]], axis=1)
sys_data_new_12.head()

,sys_1,Host pauling electronegativity_x,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,Host work function(eV)_y,Host pauling electronegativity_y
0,Cr,,130.0,9.203965e+06,44.0,101.07,5,710.18,12370,1.05,4.71,2.2
1,Cr,,130.0,9.203965e+06,44.0,101.07,5,710.18,12370,1.05,4.71,2.2
2,V,,130.0,9.203965e+06,44.0,101.07,5,710.18,12370,1.05,4.71,2.2
3,Cr,,130.0,9.203965e+06,44.0,101.07,5,710.18,12370,1.05,4.71,2.2
4,V,,130.0,9.203965e+06,44.0,101.07,5,710.18,12370,1.05,4.71,2.2

In [20]:
sys_data_new_13 = sys_data_new_3.merge(elem_data,
                                       left_on='sys_2',
                                       right_on='System',
                                       how='left')
sys_data_new_13 = sys_data_new_13.drop(sys_data_new_13.columns[[1,2,3,4,5,6,7,8,9,10,11]], axis=1)
sys_data_new_13.head()

,sys_2,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,Host work function(eV)_y,Host pauling electronegativity_y
0,Fe,140.0,1.149553e+07,26.0,55.845,4,746.47,7874,0.164,4.50,1.83
1,Tc,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
2,Ir,135.0,1.030733e+07,77.0,192.217,6,865.19,22650,1.566,5.27,2.2
3,Tc,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
4,W,145.0,1.277171e+07,73.0,180.948,6,728.42,16650,0.323,4.25,1.5

In [21]:
clean_setup = pd.concat([sys_data_new_11, sys_data_new_12, sys_data_new_13], axis=1)
clean_setup = clean_setup.reset_index(drop=True)
clean_setup.head()

,sys_0,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,Host work function(eV)_y,...,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,Host work function(eV)_y,Host pauling electronegativity_y
0,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,...,140.0,1.149553e+07,26.0,55.845,4,746.47,7874,0.164,4.50,1.83
1,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
2,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,...,135.0,1.030733e+07,77.0,192.217,6,865.19,22650,1.566,5.27,2.2
3,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
4,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,4.28,...,145.0,1.277171e+07,73.0,180.948,6,728.42,16650,0.323,4.25,1.5

In [22]:
clean_setup['System'], clean_setup['Formation Energy (eV)'] = sys_data['Formula'], datax['Formation Energy (eV)']
clean_setup.insert(0, 'System', clean_setup.pop('System'))
clean_setup.insert(1, 'Formation Energy (eV)', clean_setup.pop('Formation Energy (eV)'))

clean_setup.head()

,System,Formation Energy (eV),sys_0,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,...,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,Host work function(eV)_y,Host pauling electronegativity_y
0,Al2CrFe,2.471,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,...,140.0,1.149553e+07,26.0,55.845,4,746.47,7874,0.164,4.50,1.83
1,Al2CrTc,2.714,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
2,Al2VIr,2.600,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,...,135.0,1.030733e+07,77.0,192.217,6,865.19,22650,1.566,5.27,2.2
3,AlCrTc2,3.306,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
4,AlV2W,3.756,Al,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,...,145.0,1.277171e+07,73.0,180.948,6,728.42,16650,0.323,4.25,1.5

In [23]:
clean_setup_2 = clean_setup.drop(clean_setup.columns[[2,13,14,25]], axis=1)
clean_setup_2.head()

,System,Formation Energy (eV),Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,...,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,Host work function(eV)_y,Host pauling electronegativity_y
0,Al2CrFe,2.471,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,140.0,1.149553e+07,26.0,55.845,4,746.47,7874,0.164,4.50,1.83
1,Al2CrTc,2.714,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
2,Al2VIr,2.600,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,135.0,1.030733e+07,77.0,192.217,6,865.19,22650,1.566,5.27,2.2
3,AlCrTc2,3.306,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
4,AlV2W,3.756,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,145.0,1.277171e+07,73.0,180.948,6,728.42,16650,0.323,4.25,1.5

In [24]:
clean_data = clean_setup_2.dropna().reset_index(drop=True)
clean_data.head()

,System,Formation Energy (eV),Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,...,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,Host work function(eV)_y,Host pauling electronegativity_y
0,Al2CrFe,2.471,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,140.0,1.149553e+07,26.0,55.845,4,746.47,7874,0.164,4.50,1.83
1,Al2CrTc,2.714,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
2,Al2VIr,2.600,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,135.0,1.030733e+07,77.0,192.217,6,865.19,22650,1.566,5.27,2.2
3,AlCrTc2,3.306,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
4,AlV2W,3.756,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,145.0,1.277171e+07,73.0,180.948,6,728.42,16650,0.323,4.25,1.5

In [25]:
clean_test = clean_data[(clean_data != 0).all(1)].reset_index(drop=True)
clean_test.head()

,System,Formation Energy (eV),Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,...,Host radius(pm)_y,Host volume_y,Host atomic number_y,Host atomic mass_y,Host period_y,Host ionization energy(KJ/mol)_y,Host density(Kg/m3)_y,Host electron affinity_y,Host work function(eV)_y,Host pauling electronegativity_y
0,Al2CrFe,2.471,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,140.0,1.149553e+07,26.0,55.845,4,746.47,7874,0.164,4.50,1.83
1,Al2CrTc,2.714,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
2,Al2VIr,2.600,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,135.0,1.030733e+07,77.0,192.217,6,865.19,22650,1.566,5.27,2.2
3,AlCrTc2,3.306,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,135.0,1.030733e+07,43.0,98,5,686.92,11500,0.550,4.90,1.9
4,AlV2W,3.756,125.0,8.182292e+06,13.0,26.9815,3,577.54,2700,0.442,...,145.0,1.277171e+07,73.0,180.948,6,728.42,16650,0.323,4.25,1.5

In [26]:
clean_test.to_excel(r'C:\Users\Damilola Ologunagba\Desktop\Clean Data_v5.xlsx', index = False)